### ISSUE TITLE
issue when trying to use mvn pakage

### ISSUE THREAD

**Issue by Napoleon-x** [sim0n/Nemesis#3]
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:00 min
[INFO] Finished at: 2021-03-16T20:00:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nemesis: Could not resolve dependencies for project dev.sim0n:nemesis:jar:1.0-SNAPSHOT: Could not find artifact org.bukkit:craftbukkit:jar:1.8.8-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by Napoleon-x** [comment]
oh wait, nvm

**Comment by tyronetheqt** [comment]
> oh wait, nvm

how did u fix it
